version: "3"
services:
  brainfuck_interpreter:
    image: brainfuck_interpreter
    container_name: brainfuck_interpreter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
