name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --all-targets --all-features
